version: '3'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=safebsc
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    volumes:
      - /home/ubuntu/mongodb/data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27017/safebsc --quiet
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:
