version: '3'
services:
  app2:
    build:
      dockerfile: ./deployments/Dockerfile.prod
      context: .
    restart: unless-stopped
    ports:
    - "8080:8080"
    networks:
      - backend

networks:
  backend: