version: '3'

services:
  app:
    build:
      dockerfile: ./deployments/Dockerfile.prod
      context: .
    restart: unless-stopped
    ports:
    - "9100:9100"
    networks:
      - backend

networks:
  backend: